### ISSUE TITLE
Forbidden on add user

### ISSUE THREAD

**Issue by muflone** [thorsten/phpMyFAQ#1216]
Whenever I want to add a new user a forbidden page appears.
The apache log shows:

    [23/Jul/2016:19:53:08 -0500] "POST /admin/?action=user&user_action=addsave HTTP/1.1" 403 327 "http://faq.muflone.com/admin/?action=user&user_action=add" "Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"

PHPMyFaq 2.9.2
Web server: apache
PHP: 5.6
Database: mysql 5.5.28-29.2

**Comment by thorsten** [comment]
Do you use "Log me on automatically next time"?

**Comment by muflone** [comment]
No, I don't use the log me automatically feature on login

**Comment by thorsten** [comment]
Adding user's works for me on pre-2.9.3, because I think I fixed it with https://github.com/thorsten/phpMyFAQ/commit/92be383f12de4ddfc2382dc5b7a30b32ea0b6855
Would it be possible to apply this patch and test it again?

**Comment by muflone** [comment]
Unfortunately that's not enough, the issue remains.
On new user saving the server replies:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /admin/
on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

**Comment by thorsten** [comment]
Okay, I checked everything. Looks like your server denies the request, but I don't why. phpMyFAQ doesn't send a 403, it's your Apache.

**Comment by muflone** [comment]
I managed to install phpmyfaq 2.9.2 into another webserver and everything worked fine.
I don't know what's wrong in the first web server.
