### ISSUE TITLE
phpMyFAQ login menu without url of the administration page

### ISSUE THREAD

**Issue by neemiasjr** [thorsten/phpMyFAQ#1247]
Dear, the url to the administration page is not displayed in the upper right corner of phpMyFAQ in version 2.9.5
![phpmyfaq-295](https://cloud.githubusercontent.com/assets/19786154/18218627/67d971c8-713a-11e6-832b-c87a4570911d.png)

**Comment by thorsten** [comment]
Thanks for reporting this issue. Which language are you using?

**Comment by neemiasjr** [comment]
Yes, this user is Administrator and went to the administration page. The problem is only that does not appear the page link in the menu.

**Comment by neemiasjr** [comment]
![admin page - phpmyfaq](https://cloud.githubusercontent.com/assets/19786154/18254003/beb8829a-736f-11e6-88d0-355fe25a9911.png)

**Comment by thorsten** [comment]
Which permissions does the user has? All of them?

**Comment by neemiasjr** [comment]
![admin page - usuario neemias](https://cloud.githubusercontent.com/assets/19786154/18257406/94e912a2-7399-11e6-9788-aa84b69efd0e.png)

**Comment by thorsten** [comment]
Okay, will try to reproduce it.

**Comment by thorsten** [comment]
Should be fixed, now.

**Comment by neemiasjr** [comment]
Dear, even changing informed source, the problem still remains. I realized that in index.php to the administration page appears it is necessary that the user has the minimum permissions 37, 39, 40, 41. But my faqright table does not have the code 37 and 38. So that the administration page it's not showing. What are the records of this table. Thank you.

**Comment by neemiasjr** [comment]
![faqright table](https://cloud.githubusercontent.com/assets/19786154/18358303/ce43e8aa-75ca-11e6-95a4-c5b2aa2c1c47.png)

**Comment by thorsten** [comment]
These are the missing queries:

`INSERT INTO faqright (right_id,name,description,for_users,for_groups)
VALUES
	(37, 'dlattachment', 'Right to download attachments', 1, 1),
	(38, 'reports', 'Right to generate reports', 1, 1);
`

**Comment by neemiasjr** [comment]
Thank you!

**Comment by thorsten** [comment]
Is it working now?

**Comment by neemiasjr** [comment]
After selecting the new permissions added to the Administration page, returned to work. But I saw the faqright table contains duplicate records, as dump the attachment table.

[phpmyfaq-faqright.txt](https://github.com/thorsten/phpMyFAQ/files/462279/phpmyfaq-faqright.txt)

**Comment by neemiasjr** [comment]
Records 35,36,37,38.
