### ISSUE TITLE
Seems impossible to reinstall 3.0

### ISSUE THREAD

**Issue by scottcwilson** [thorsten/phpMyFAQ#1526]
I keep getting Error while fetching result: Table 'phpmyfaq.faqconfig' doesn't existError while fetching result: Table 'phpmyfaq.faqconfig' doesn't existError while fetching result: Table 'phpmyfaq.faqconfig' doesn't existError while fetching result: Table 'phpmyfaq.faqconfig' doesn't exist

Also the command referenced in README.md:
Then just open http://www.example.org/phpmyfaq/install/setup.php in your browser.
no longer works.

**Comment by thorsten** [comment]
I fixed the wrong URL, it's http://www.example.org/phpmyfaq/setup/index.php in the 3.0 release

**Comment by scottcwilson** [comment]
Still doesn't work. 

This one gives me the message 
To install phpMyFAQ please use the Setup

When I click the Setup, I get
It seems you're already running a version of phpMyFAQ. Please use the update script.

When I click the update script, I get 
Error while fetching result: Table 'phpmyfaq.faqconfig' doesn't existError while fetching result: Table 'phpmyfaq.faqconfig' doesn't existError while fetching result: Table 'phpmyfaq.faqconfig' doesn't existError while fetching result: Table 'phpmyfaq.faqconfig' doesn't exist

**Comment by thorsten** [comment]
Do you still have a database.php file in your config folder? If yes, please delete it.

**Comment by scottcwilson** [comment]
That did the trick.  Now can you detect this condition and advise in the installation script?
