### ISSUE TITLE
docker-composer from fresh clone has errors and is unusable

### ISSUE THREAD

**Issue by TheSin-** [thorsten/phpMyFAQ#1655]
I just setup a fresh git clone and a freshly installs Debian 10.3 server, I installed docker from docker direct, and the latest docker-composer.

I then run `docker-composer up` and I get elasticsearch errors, also the setup page is full white when I added error out to the setup page it complains that it can't fine autoload.php

```
elasticsearch-v6 | [2020-03-02T20:24:27,738][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
elasticsearch-v6 | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch-v6 | 	at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	... 6 more
elasticsearch-v6 | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch-v6 | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch-v6 | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch-v6 | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch-v6 | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
elasticsearch-v6 | 	at java.nio.file.Files.createDirectory(Files.java:693) ~[?:?]
elasticsearch-v6 | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:800) ~[?:?]
elasticsearch-v6 | 	at java.nio.file.Files.createDirectories(Files.java:786) ~[?:?]
elasticsearch-v6 | 	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.6.jar:6.8.6]
elasticsearch-v6 | 	... 6 more
elasticsearch-v6 exited with code 1
```

I'm also seeing errors about gd being missing.  Which I assume is the issue with autoloader.php

```
composer_1       | Loading composer repositories with package information
composer_1       | Installing dependencies from lock file
composer_1       | Dependency resolution completed in 0.000 seconds
composer_1       | Your requirements could not be resolved to an installable set of packages.
composer_1       | 
composer_1       |   Problem 1
composer_1       |     - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
composer_1       | 
phpmyfaq_composer_1 exited with code 2
```

I've tried to remove all images completely and restarting it's always the same.

**Comment by thorsten** [comment]
You used the master branch, right?

**Comment by TheSin-** [comment]
I did yes.

**Comment by thorsten** [comment]
Fixed with d1723328ccc864ae46ac9c02ff54b511f337a7fd

**Comment by pocketrocket** [comment]
@thorsten Issue still is active in master, though it seems like you patched that commit around?
"Fixed with `d172332`" is in master `560b4dc215`

on top it now fails with:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.postgres.volumes contains an invalid type, it should be a string, or an object
```

**Comment by thorsten** [comment]
I’ll take a look!

**Comment by thorsten** [comment]
Started clean with

```
$ docker-compose rm
$ docker system prune --volumes
```

When I started on the master branch:

`$ docker-compose up`

And it works for me:

```
 thorsten@iMac  ~/htdocs/phpmyFAQ   master ? ↑1 ⍟1  docker-compose up                                                                                                                                                                                                                          ✔  3395  06:00:57
Creating network "phpmyfaq_default" with the default driver
Creating phpmyfaq_postgres_1   ... done
Creating elasticsearch-v6    ... done
Creating phpmyfaq_mariadb_1  ... done
Creating phpmyfaq_composer_1   ... done
Creating phpmyfaq_phpmyadmin_1 ... done
Creating phpmyfaq_yarn_1       ... done
Creating phpmyfaq_phpmyfaq_1   ... done
Attaching to elasticsearch-v6, phpmyfaq_mariadb_1, phpmyfaq_composer_1, phpmyfaq_postgres_1, phpmyfaq_phpmyadmin_1, phpmyfaq_yarn_1, phpmyfaq_phpmyfaq_1
elasticsearch-v6 | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
composer_1       | Loading composer repositories with package information
composer_1       | Installing dependencies from lock file
composer_1       | Dependency resolution completed in 0.000 seconds
composer_1       | Your requirements could not be resolved to an installable set of packages.
composer_1       | 
composer_1       |   Problem 1
composer_1       |     - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
composer_1       | 
phpmyadmin_1     | phpMyAdmin not found in /var/www/html - copying now...
phpmyfaq_composer_1 exited with code 2
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] mysqld (mysqld 10.2.14-MariaDB-10.2.14+maria~jessie) starting as process 1 ...
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Uses event mutexes
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Using Linux native AIO
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Number of pools: 1
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1        | 2020-04-24  4:02:19 140676861118208 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Highest supported file format is Barracuda.
phpmyfaq_1       | Enabling module rewrite.
phpmyfaq_1       | Enabling module headers.
phpmyfaq_1       | To activate the new configuration, you need to run:
phpmyfaq_1       |   service apache2 restart
phpmyfaq_1       | # php settings:
phpmyfaq_1       | register_globals = Off
phpmyfaq_1       | safe_mode = Off
phpmyfaq_1       | log_errors = "On"
phpmyfaq_1       | error_reporting = "E_ALL & E_DEPRECATED & E_STRICT"
phpmyfaq_1       | date.timezone = "Europe/Berlin"
phpmyfaq_1       | memory_limit = "128M"
phpmyfaq_1       | file_upload = "On"
phpmyfaq_1       | post_max_size = 64M
phpmyfaq_1       | upload_max_filesize = 64M
phpmyfaq_1       | opcache.memory_consumption=128
phpmyfaq_1       | opcache.interned_strings_buffer=8
phpmyfaq_1       | opcache.max_accelerated_files=4000
phpmyfaq_1       | opcache.revalidate_freq=2
phpmyfaq_1       | opcache.fast_shutdown=1
phpmyfaq_1       | opcache.enable_cli=1
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1        | 2020-04-24  4:02:19 140677597525888 [Note] InnoDB: Waiting for purge to start
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Note] InnoDB: 5.7.21 started; log sequence number 5550821
mariadb_1        | 2020-04-24  4:02:20 140676285069056 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
phpmyfaq_1       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.8. Set the 'ServerName' directive globally to suppress this message
phpmyfaq_1       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.8. Set the 'ServerName' directive globally to suppress this message
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Warning] Failed to create a socket for IPv6 '::': errno: 97.
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Note] Server socket created on IP: '0.0.0.0'.
phpmyfaq_1       | [Fri Apr 24 04:02:20.114405 2020] [mpm_prefork:notice] [pid 28] AH00163: Apache/2.4.38 (Debian) PHP/7.4.0 configured -- resuming normal operations
phpmyfaq_1       | [Fri Apr 24 04:02:20.114491 2020] [core:notice] [pid 28] AH00094: Command line: 'apache2 -D FOREGROUND'
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Warning] 'proxies_priv' entry '@% root@14db14cab73f' ignored in --skip-name-resolve mode.
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Note] Reading of all Master_info entries succeded
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Note] Added new Master_info '' to hash table
mariadb_1        | 2020-04-24  4:02:20 140677597525888 [Note] mysqld: ready for connections.
mariadb_1        | Version: '10.2.14-MariaDB-10.2.14+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1        | 2020-04-24  4:02:20 140676285069056 [Note] InnoDB: Buffer pool(s) load completed at 200424  4:02:20
phpmyadmin_1     | Complete! phpMyAdmin has been successfully copied to /var/www/html
phpmyadmin_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
phpmyadmin_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
phpmyadmin_1     | [Fri Apr 24 04:02:20.533866 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.2.23 configured -- resuming normal operations
phpmyadmin_1     | [Fri Apr 24 04:02:20.533960 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
postgres_1       | 2020-04-24 04:02:21.231 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1       | 2020-04-24 04:02:21.235 UTC [1] LOG:  could not create IPv6 socket for address "::": Address family not supported by protocol
postgres_1       | 2020-04-24 04:02:21.266 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2020-04-24 04:02:21.333 UTC [23] LOG:  database system was shut down at 2020-04-24 03:59:33 UTC
postgres_1       | 2020-04-24 04:02:21.355 UTC [1] LOG:  database system is ready to accept connections
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
elasticsearch-v6 | [2020-04-24T04:02:21,684][INFO ][o.e.e.NodeEnvironment    ] [NM89Cuq] using [1] data paths, mounts [[/usr/share/elasticsearch/data (osxfs)]], net usable_space [24.3gb], net total_space [465.6gb], types [fuse.osxfs]
elasticsearch-v6 | [2020-04-24T04:02:21,686][INFO ][o.e.e.NodeEnvironment    ] [NM89Cuq] heap size [494.9mb], compressed ordinary object pointers [true]
elasticsearch-v6 | [2020-04-24T04:02:21,695][INFO ][o.e.n.Node               ] [NM89Cuq] node name derived from node ID [NM89CuqlTtO1JKTDEnsLrg]; set [node.name] to override
elasticsearch-v6 | [2020-04-24T04:02:21,696][INFO ][o.e.n.Node               ] [NM89Cuq] version[6.8.7], pid[1], build[default/docker/c63e621/2020-02-26T14:38:01.193138Z], OS[Linux/4.19.76-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8]
elasticsearch-v6 | [2020-04-24T04:02:21,696][INFO ][o.e.n.Node               ] [NM89Cuq] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-8301223745214594808, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker]
elasticsearch-v6 | [2020-04-24T04:02:22,920][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [aggs-matrix-stats]
elasticsearch-v6 | [2020-04-24T04:02:22,920][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [analysis-common]
elasticsearch-v6 | [2020-04-24T04:02:22,920][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [ingest-common]
elasticsearch-v6 | [2020-04-24T04:02:22,920][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [ingest-geoip]
elasticsearch-v6 | [2020-04-24T04:02:22,920][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [ingest-user-agent]
elasticsearch-v6 | [2020-04-24T04:02:22,921][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [lang-expression]
elasticsearch-v6 | [2020-04-24T04:02:22,921][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [lang-mustache]
elasticsearch-v6 | [2020-04-24T04:02:22,921][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [lang-painless]
elasticsearch-v6 | [2020-04-24T04:02:22,921][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [mapper-extras]
elasticsearch-v6 | [2020-04-24T04:02:22,921][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [parent-join]
elasticsearch-v6 | [2020-04-24T04:02:22,922][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [percolator]
elasticsearch-v6 | [2020-04-24T04:02:22,922][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [rank-eval]
elasticsearch-v6 | [2020-04-24T04:02:22,922][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [reindex]
elasticsearch-v6 | [2020-04-24T04:02:22,922][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [repository-url]
elasticsearch-v6 | [2020-04-24T04:02:22,922][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [transport-netty4]
elasticsearch-v6 | [2020-04-24T04:02:22,923][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [tribe]
elasticsearch-v6 | [2020-04-24T04:02:22,923][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-ccr]
elasticsearch-v6 | [2020-04-24T04:02:22,923][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-core]
elasticsearch-v6 | [2020-04-24T04:02:22,924][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-deprecation]
elasticsearch-v6 | [2020-04-24T04:02:22,924][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-graph]
elasticsearch-v6 | [2020-04-24T04:02:22,924][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-ilm]
elasticsearch-v6 | [2020-04-24T04:02:22,924][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-logstash]
elasticsearch-v6 | [2020-04-24T04:02:22,924][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-ml]
elasticsearch-v6 | [2020-04-24T04:02:22,925][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-monitoring]
elasticsearch-v6 | [2020-04-24T04:02:22,925][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-rollup]
elasticsearch-v6 | [2020-04-24T04:02:22,925][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-security]
elasticsearch-v6 | [2020-04-24T04:02:22,925][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-sql]
elasticsearch-v6 | [2020-04-24T04:02:22,926][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-upgrade]
elasticsearch-v6 | [2020-04-24T04:02:22,926][INFO ][o.e.p.PluginsService     ] [NM89Cuq] loaded module [x-pack-watcher]
elasticsearch-v6 | [2020-04-24T04:02:22,927][INFO ][o.e.p.PluginsService     ] [NM89Cuq] no plugins loaded
elasticsearch-v6 | [2020-04-24T04:02:25,426][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [NM89Cuq] [controller/86] [Main.cc@109] controller (64 bit): Version 6.8.7 (Build f3f0534e9623b3) Copyright (c) 2020 Elasticsearch BV
phpmyfaq_1       | 172.18.0.1 - - [24/Apr/2020:04:02:25 +0000] "POST /inform HTTP/1.1" 404 663 "-" "AirControl Agent v1.0"
elasticsearch-v6 | [2020-04-24T04:02:26,004][INFO ][o.e.d.DiscoveryModule    ] [NM89Cuq] using discovery type [zen] and host providers [settings]
elasticsearch-v6 | [2020-04-24T04:02:26,588][INFO ][o.e.n.Node               ] [NM89Cuq] initialized
elasticsearch-v6 | [2020-04-24T04:02:26,588][INFO ][o.e.n.Node               ] [NM89Cuq] starting ...
elasticsearch-v6 | [2020-04-24T04:02:26,683][INFO ][o.e.t.TransportService   ] [NM89Cuq] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch-v6 | [2020-04-24T04:02:26,703][INFO ][o.e.b.BootstrapChecks    ] [NM89Cuq] bound or publishing to a non-loopback address, enforcing bootstrap checks
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass
yarn_1           | 
yarn_1           | > node-sass@4.14.0 install /usr/local/lib/node_modules/node-sass
yarn_1           | > node scripts/install.js
yarn_1           | 
yarn_1           | Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.0/linux-x64-64_binding.node
elasticsearch-v6 | [2020-04-24T04:02:29,740][INFO ][o.e.c.s.MasterService    ] [NM89Cuq] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {NM89Cuq}{NM89CuqlTtO1JKTDEnsLrg}{PqHLUJPdRue3V-Km3mKJWA}{172.18.0.2}{172.18.0.2:9300}{ml.machine_memory=2089971712, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}
elasticsearch-v6 | [2020-04-24T04:02:29,743][INFO ][o.e.c.s.ClusterApplierService] [NM89Cuq] new_master {NM89Cuq}{NM89CuqlTtO1JKTDEnsLrg}{PqHLUJPdRue3V-Km3mKJWA}{172.18.0.2}{172.18.0.2:9300}{ml.machine_memory=2089971712, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}, reason: apply cluster state (from master [master {NM89Cuq}{NM89CuqlTtO1JKTDEnsLrg}{PqHLUJPdRue3V-Km3mKJWA}{172.18.0.2}{172.18.0.2:9300}{ml.machine_memory=2089971712, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
elasticsearch-v6 | [2020-04-24T04:02:29,803][INFO ][o.e.h.n.Netty4HttpServerTransport] [NM89Cuq] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch-v6 | [2020-04-24T04:02:29,803][INFO ][o.e.n.Node               ] [NM89Cuq] started
elasticsearch-v6 | [2020-04-24T04:02:29,986][INFO ][o.e.l.LicenseService     ] [NM89Cuq] license [45bf763b-7e98-4e1f-b3d2-8f68363572a6] mode [basic] - valid
elasticsearch-v6 | [2020-04-24T04:02:29,992][INFO ][o.e.g.GatewayService     ] [NM89Cuq] recovered [0] indices into cluster_state
Download complete..] - :
yarn_1           | Binary saved to /usr/local/lib/node_modules/node-sass/vendor/linux-x64-64/binding.node
yarn_1           | Caching binary to /root/.npm/node-sass/4.14.0/linux-x64-64_binding.node

yarn_1           | > node-sass@4.14.0 postinstall /usr/local/lib/node_modules/node-sass
yarn_1           | > node scripts/build.js
yarn_1           | 
yarn_1           | Binary found at /usr/local/lib/node_modules/node-sass/vendor/linux-x64-64/binding.node
yarn_1           | Testing binary
yarn_1           | Binary is fine
yarn_1           | + node-sass@4.14.0
yarn_1           | added 172 packages from 137 contributors in 11.129s
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
phpmyfaq_1       | 172.18.0.1 - - [24/Apr/2020:04:02:33 +0000] "POST /inform HTTP/1.1" 404 663 "-" "AirControl Agent v1.0"
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
elasticsearch-v6 | [2020-04-24T04:02:59,786][WARN ][o.e.c.r.a.DiskThresholdMonitor] [NM89Cuq] high disk watermark [90%] exceeded on [NM89CuqlTtO1JKTDEnsLrg][NM89Cuq][/usr/share/elasticsearch/data/nodes/0] free: 24gb[5.1%], shards will be relocated away from this node
elasticsearch-v6 | [2020-04-24T04:02:59,787][INFO ][o.e.c.r.a.DiskThresholdMonitor] [NM89Cuq] rerouting shards: [high disk watermark exceeded on one or more nodes]
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.21.1".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
Done in 52.14s.
yarn run v1.21.1
$ webpack
yarn_1           | (node:126) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
elasticsearch-v6 | [2020-04-24T04:03:29,795][WARN ][o.e.c.r.a.DiskThresholdMonitor] [NM89Cuq] high disk watermark [90%] exceeded on [NM89CuqlTtO1JKTDEnsLrg][NM89Cuq][/usr/share/elasticsearch/data/nodes/0] free: 24.9gb[5.3%], shards will be relocated away from this node
yarn_1           | Hash: bafa07ef8fe4802275e0
yarn_1           | Version: webpack 4.42.1
yarn_1           | Time: 3322ms
yarn_1           | Built at: 04/24/2020 4:03:31 AM
yarn_1           |                                                                       Asset        Size  Chunks                    Chunk Names
yarn_1           |     ../../../phpmyfaq/admin/assets/js/editor/plugins/phpmyfaq/plugin.min.js   919 bytes          [emitted]         
yarn_1           |                       ../../admin/assets/js/editor/plugins/advlist/index.js   205 bytes          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/advlist/plugin.js    5.52 KiB          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/advlist/plugin.min.js    2.17 KiB          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/anchor/index.js   202 bytes          [emitted]         
yarn_1           |                       ../../admin/assets/js/editor/plugins/anchor/plugin.js    3.35 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/anchor/plugin.min.js    1.41 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/autolink/index.js   208 bytes          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/autolink/plugin.js    5.76 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/autolink/plugin.min.js    2.08 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/autoresize/index.js   214 bytes          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/autoresize/plugin.js    5.58 KiB          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/autoresize/plugin.min.js    2.03 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/autosave/index.js   208 bytes          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/autosave/plugin.js    6.71 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/autosave/plugin.min.js    2.79 KiB          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/bbcode/index.js   202 bytes          [emitted]         
yarn_1           |                       ../../admin/assets/js/editor/plugins/bbcode/plugin.js    3.95 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/bbcode/plugin.min.js    2.78 KiB          [emitted]         
yarn_1           |                       ../../admin/assets/js/editor/plugins/charmap/index.js   205 bytes          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/charmap/plugin.js    22.7 KiB          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/charmap/plugin.min.js     8.4 KiB          [emitted]         
yarn_1           |                          ../../admin/assets/js/editor/plugins/code/index.js   196 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/code/plugin.js     2.4 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/code/plugin.min.js       1 KiB          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/codesample/css/prism.css    2.28 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/codesample/index.js   214 bytes          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/codesample/plugin.js    34.6 KiB          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/codesample/plugin.min.js    18.9 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/colorpicker/index.js   217 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/colorpicker/plugin.js    3.48 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/plugins/colorpicker/plugin.min.js    1.32 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/contextmenu/index.js   217 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/contextmenu/plugin.js     4.8 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/plugins/contextmenu/plugin.min.js    1.78 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/directionality/index.js   226 bytes          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/directionality/plugin.js    1.85 KiB          [emitted]         
yarn_1           |           ../../admin/assets/js/editor/plugins/directionality/plugin.min.js   857 bytes          [emitted]         
yarn_1           |          ../../admin/assets/js/editor/plugins/emoticons/img/smiley-cool.gif   354 bytes          [emitted]         
yarn_1           |           ../../admin/assets/js/editor/plugins/emoticons/img/smiley-cry.gif   329 bytes          [emitted]         
yarn_1           |    ../../admin/assets/js/editor/plugins/emoticons/img/smiley-embarassed.gif   331 bytes          [emitted]         
yarn_1           | ../../admin/assets/js/editor/plugins/emoticons/img/smiley-foot-in-mouth.gif   342 bytes          [emitted]         
yarn_1           |         ../../admin/assets/js/editor/plugins/emoticons/img/smiley-frown.gif   340 bytes          [emitted]         
yarn_1           |      ../../admin/assets/js/editor/plugins/emoticons/img/smiley-innocent.gif   336 bytes          [emitted]         
yarn_1           |          ../../admin/assets/js/editor/plugins/emoticons/img/smiley-kiss.gif   338 bytes          [emitted]         
yarn_1           |      ../../admin/assets/js/editor/plugins/emoticons/img/smiley-laughing.gif   343 bytes          [emitted]         
yarn_1           |   ../../admin/assets/js/editor/plugins/emoticons/img/smiley-money-mouth.gif   321 bytes          [emitted]         
yarn_1           |        ../../admin/assets/js/editor/plugins/emoticons/img/smiley-sealed.gif   323 bytes          [emitted]         
yarn_1           |         ../../admin/assets/js/editor/plugins/emoticons/img/smiley-smile.gif   344 bytes          [emitted]         
yarn_1           |     ../../admin/assets/js/editor/plugins/emoticons/img/smiley-surprised.gif   338 bytes          [emitted]         
yarn_1           |    ../../admin/assets/js/editor/plugins/emoticons/img/smiley-tongue-out.gif   328 bytes          [emitted]         
yarn_1           |     ../../admin/assets/js/editor/plugins/emoticons/img/smiley-undecided.gif   337 bytes          [emitted]         
yarn_1           |          ../../admin/assets/js/editor/plugins/emoticons/img/smiley-wink.gif   350 bytes          [emitted]         
yarn_1           |          ../../admin/assets/js/editor/plugins/emoticons/img/smiley-yell.gif   336 bytes          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/emoticons/index.js   211 bytes          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/emoticons/plugin.js    2.31 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/emoticons/plugin.min.js    1.05 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/fullpage/index.js   208 bytes          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/fullpage/plugin.js    16.7 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/fullpage/plugin.min.js       7 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/fullscreen/index.js   214 bytes          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/fullscreen/plugin.js    5.46 KiB          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/fullscreen/plugin.min.js    2.13 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/help/img/logo.png    12.9 KiB          [emitted]         
yarn_1           |                          ../../admin/assets/js/editor/plugins/help/index.js   196 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/help/plugin.js    16.5 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/help/plugin.min.js    7.99 KiB          [emitted]         
yarn_1           |                            ../../admin/assets/js/editor/plugins/hr/index.js   190 bytes          [emitted]         
yarn_1           |                           ../../admin/assets/js/editor/plugins/hr/plugin.js   919 bytes          [emitted]         
yarn_1           |                       ../../admin/assets/js/editor/plugins/hr/plugin.min.js   428 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/image/index.js   199 bytes          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/image/plugin.js    39.1 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/image/plugin.min.js    15.5 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/imagetools/index.js   214 bytes          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/imagetools/plugin.js    84.4 KiB          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/imagetools/plugin.min.js    31.6 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/importcss/index.js   211 bytes          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/importcss/plugin.js    9.25 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/importcss/plugin.min.js    3.06 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/insertdatetime/index.js   226 bytes          [emitted]         
yarn_1           |               ../../admin/assets/js/editor/plugins/insertdatetime/plugin.js    6.03 KiB          [emitted]         
yarn_1           |           ../../admin/assets/js/editor/plugins/insertdatetime/plugin.min.js    2.57 KiB          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/legacyoutput/index.js   220 bytes          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/legacyoutput/plugin.js     6.8 KiB          [emitted]         
yarn_1           |             ../../admin/assets/js/editor/plugins/legacyoutput/plugin.min.js    3.32 KiB          [emitted]         
yarn_1           |                          ../../admin/assets/js/editor/plugins/link/index.js   196 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/link/plugin.js    23.4 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/link/plugin.min.js    8.73 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/lists/index.js   199 bytes          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/lists/plugin.js    68.8 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/lists/plugin.min.js    26.3 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/media/index.js   199 bytes          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/media/plugin.js      37 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/media/plugin.min.js    14.7 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/nonbreaking/index.js   217 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/nonbreaking/plugin.js    2.42 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/plugins/nonbreaking/plugin.min.js  1010 bytes          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/noneditable/index.js   217 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/noneditable/plugin.js     4.2 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/plugins/noneditable/plugin.min.js     1.5 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/pagebreak/index.js   211 bytes          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/pagebreak/plugin.js    3.42 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/pagebreak/plugin.min.js     1.4 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/paste/index.js   199 bytes          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/paste/plugin.js    80.4 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/paste/plugin.min.js    30.1 KiB          [emitted]         
yarn_1           |                       ../../admin/assets/js/editor/plugins/preview/index.js   205 bytes          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/preview/plugin.js    4.43 KiB          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/preview/plugin.min.js       2 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/print/index.js   199 bytes          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/print/plugin.js    1.03 KiB          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/print/plugin.min.js   465 bytes          [emitted]         
yarn_1           |                          ../../admin/assets/js/editor/plugins/save/index.js   196 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/save/plugin.js     3.3 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/save/plugin.min.js    1.39 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/searchreplace/index.js   223 bytes          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/searchreplace/plugin.js    20.1 KiB          [emitted]         
yarn_1           |            ../../admin/assets/js/editor/plugins/searchreplace/plugin.min.js    7.18 KiB          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/spellchecker/index.js   220 bytes          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/spellchecker/plugin.js    27.4 KiB          [emitted]         
yarn_1           |             ../../admin/assets/js/editor/plugins/spellchecker/plugin.min.js    10.1 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/tabfocus/index.js   208 bytes          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/tabfocus/plugin.js    3.63 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/tabfocus/plugin.min.js    1.58 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/plugins/table/index.js   199 bytes          [emitted]         
yarn_1           |                        ../../admin/assets/js/editor/plugins/table/plugin.js     306 KiB          [emitted]  [big]  
yarn_1           |                    ../../admin/assets/js/editor/plugins/table/plugin.min.js     116 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/template/index.js   208 bytes          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/template/plugin.js    11.9 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/template/plugin.min.js    5.07 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/textcolor/index.js   211 bytes          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/textcolor/plugin.js      11 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/textcolor/plugin.min.js    4.81 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/textpattern/index.js   217 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/textpattern/plugin.js    18.6 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/plugins/textpattern/plugin.min.js    7.23 KiB          [emitted]         
yarn_1           |                           ../../admin/assets/js/editor/plugins/toc/index.js   193 bytes          [emitted]         
yarn_1           |                          ../../admin/assets/js/editor/plugins/toc/plugin.js    7.01 KiB          [emitted]         
yarn_1           |                      ../../admin/assets/js/editor/plugins/toc/plugin.min.js    2.87 KiB          [emitted]         
yarn_1           |      ../../admin/assets/js/editor/plugins/visualblocks/css/visualblocks.css    5.34 KiB          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/visualblocks/index.js   220 bytes          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/plugins/visualblocks/plugin.js    4.16 KiB          [emitted]         
yarn_1           |             ../../admin/assets/js/editor/plugins/visualblocks/plugin.min.js    1.65 KiB          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/plugins/visualchars/index.js   217 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/plugins/visualchars/plugin.js    12.8 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/plugins/visualchars/plugin.min.js     5.2 KiB          [emitted]         
yarn_1           |                     ../../admin/assets/js/editor/plugins/wordcount/index.js   211 bytes          [emitted]         
yarn_1           |                    ../../admin/assets/js/editor/plugins/wordcount/plugin.js    18.8 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/plugins/wordcount/plugin.min.js    11.8 KiB          [emitted]         
yarn_1           |         ../../admin/assets/js/editor/skins/lightgray/content.inline.min.css    3.53 KiB          [emitted]         
yarn_1           |                ../../admin/assets/js/editor/skins/lightgray/content.min.css    3.92 KiB          [emitted]         
yarn_1           |         ../../admin/assets/js/editor/skins/lightgray/content.mobile.min.css   234 bytes          [emitted]         
yarn_1           |      ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce-mobile.woff    4.52 KiB          [emitted]         
yarn_1           |        ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce-small.eot    9.27 KiB          [emitted]         
yarn_1           |        ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce-small.svg    24.1 KiB          [emitted]         
yarn_1           |        ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce-small.ttf    9.09 KiB          [emitted]         
yarn_1           |       ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce-small.woff    9.16 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce.eot    18.5 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce.svg    45.3 KiB          [emitted]         
yarn_1           |              ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce.ttf    18.3 KiB          [emitted]         
yarn_1           |             ../../admin/assets/js/editor/skins/lightgray/fonts/tinymce.woff    18.4 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/skins/lightgray/img/anchor.gif    53 bytes          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/skins/lightgray/img/loader.gif    2.55 KiB          [emitted]         
yarn_1           |                 ../../admin/assets/js/editor/skins/lightgray/img/object.gif   152 bytes          [emitted]         
yarn_1           |                  ../../admin/assets/js/editor/skins/lightgray/img/trans.gif    43 bytes          [emitted]         
yarn_1           |                   ../../admin/assets/js/editor/skins/lightgray/skin.min.css      43 KiB          [emitted]         
yarn_1           |            ../../admin/assets/js/editor/skins/lightgray/skin.mobile.min.css    27.2 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/themes/inlite/index.js   198 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/themes/inlite/theme.js     313 KiB          [emitted]  [big]  
yarn_1           |                     ../../admin/assets/js/editor/themes/inlite/theme.min.js     129 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/themes/mobile/index.js   198 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/themes/mobile/theme.js     416 KiB          [emitted]  [big]  
yarn_1           |                     ../../admin/assets/js/editor/themes/mobile/theme.min.js     160 KiB          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/themes/modern/index.js   198 bytes          [emitted]         
yarn_1           |                         ../../admin/assets/js/editor/themes/modern/theme.js     308 KiB          [emitted]  [big]  
yarn_1           |                     ../../admin/assets/js/editor/themes/modern/theme.min.js     128 KiB          [emitted]         
yarn_1           |                                 ../../admin/assets/js/editor/tinymce.min.js     356 KiB          [emitted]  [big]  
yarn_1           |                                                      ../js/libs/default.css    1.13 KiB          [emitted]         
yarn_1           |                                                ../js/libs/highlight.pack.js    1.04 MiB          [emitted]  [big]  
yarn_1           |                                                            admin-styles.css     194 KiB       0  [emitted]         admin-styles
yarn_1           |                                                             admin-styles.js   936 bytes       0  [emitted]         admin-styles
yarn_1           |                                                                  backend.js    1.37 KiB       1  [emitted]         backend
yarn_1           |                                               fonts/forkawesome-webfont.eot     185 KiB          [emitted]         
yarn_1           |                                               fonts/forkawesome-webfont.svg     470 KiB          [emitted]  [big]  
yarn_1           |                                               fonts/forkawesome-webfont.ttf     184 KiB          [emitted]         
yarn_1           |                                              fonts/forkawesome-webfont.woff     112 KiB          [emitted]         
yarn_1           |                                             fonts/forkawesome-webfont.woff2    89.5 KiB          [emitted]         
yarn_1           |                                                                 frontend.js    21.9 KiB       2  [emitted]         frontend
yarn_1           |                                                                 phpmyfaq.js    8.68 KiB          [emitted]         
yarn_1           |                                                                  styles.css     189 KiB       3  [emitted]         styles
yarn_1           |                                                                   styles.js   936 bytes       3  [emitted]         styles
yarn_1           |                                                                  vendors.js     306 KiB       4  [emitted]  [big]  vendors
yarn_1           | Entrypoint vendors [big] = vendors.js
yarn_1           | Entrypoint frontend = frontend.js
yarn_1           | Entrypoint backend = backend.js
yarn_1           | Entrypoint styles = styles.css styles.js
yarn_1           | Entrypoint admin-styles = admin-styles.css admin-styles.js
yarn_1           |  [3] (webpack)/buildin/global.js 472 bytes {4} [built]
yarn_1           | [13] ./phpmyfaq/assets/src/vendors.js 745 bytes {4} [built]
yarn_1           | [40] ./phpmyfaq/admin/assets/src/index.js 465 bytes {1} [built]
yarn_1           | [41] ./phpmyfaq/assets/themes/default/scss/style.scss 39 bytes {3} [built]
yarn_1           | [42] ./phpmyfaq/admin/assets/scss/style.scss 39 bytes {0} [built]
yarn_1           | [43] ./phpmyfaq/assets/src/frontend.js + 1 modules 1.53 KiB {2} [built]
yarn_1           |      | ./phpmyfaq/assets/src/frontend.js 650 bytes [built]
yarn_1           |      | ./phpmyfaq/assets/src/reading-time.js 912 bytes [built]
yarn_1           |     + 40 hidden modules
yarn_1           | 
yarn_1           | WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
yarn_1           | This can impact web performance.
yarn_1           | Assets: 
yarn_1           |   fonts/forkawesome-webfont.svg (470 KiB)
yarn_1           |   vendors.js (306 KiB)
yarn_1           |   ../../admin/assets/js/editor/themes/modern/theme.js (308 KiB)
yarn_1           |   ../../admin/assets/js/editor/tinymce.min.js (356 KiB)
yarn_1           |   ../../admin/assets/js/editor/plugins/table/plugin.js (306 KiB)
yarn_1           |   ../../admin/assets/js/editor/themes/inlite/theme.js (313 KiB)
yarn_1           |   ../../admin/assets/js/editor/themes/mobile/theme.js (416 KiB)
yarn_1           |   ../js/libs/highlight.pack.js (1.04 MiB)
yarn_1           | 
yarn_1           | WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
yarn_1           | Entrypoints:
yarn_1           |   vendors (306 KiB)
yarn_1           |       vendors.js
yarn_1           | 
yarn_1           | 
yarn_1           | WARNING in webpack performance recommendations: 
yarn_1           | You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
yarn_1           | For more info visit https://webpack.js.org/guides/code-splitting/
yarn_1           | Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!phpmyfaq/admin/assets/scss/style.scss:
yarn_1           |     Entrypoint mini-css-extract-plugin = *
yarn_1           |     [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./phpmyfaq/admin/assets/scss/style.scss 198 KiB {0} [built]
yarn_1           |         + 8 hidden modules
yarn_1           | Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!phpmyfaq/assets/themes/default/scss/style.scss:
yarn_1           |     Entrypoint mini-css-extract-plugin = *
yarn_1           |     [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./phpmyfaq/assets/themes/default/scss/style.scss 192 KiB {0} [built]
yarn_1           |         + 8 hidden modules
Done in 7.49s.
phpmyfaq_yarn_1 exited with code 0
phpmyfaq_1       | 172.18.0.1 - - [24/Apr/2020:04:03:56 +0000] "POST /inform HTTP/1.1" 404 663 "-" "AirControl Agent v1.0"
```

**Comment by thorsten** [comment]
@pocketrocket Anything I missed?

**Comment by pocketrocket** [comment]
@thorsten here are my steps to reproduce:

```
git fetch && git reset --hard origin/master
HEAD is now at f75c5d794 chore(deps-dev): bump phpunit/phpunit from 8.5.3 to 8.5.4

docker-compose rm
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.postgres.volumes contains an invalid type, it should be a string, or an object

vim docker-compose.yml (removing line 30 which is causing the error above)

docker-compose rm
Going to remove phpmyfaq_phpmyfaq_1, phpmyfaq_yarn_1, phpmyfaq_phpmyadmin_1, elasticsearch-v6, phpmyfaq_postgres_1, phpmyfaq_composer_1, phpmyfaq_mariadb_1
Are you sure? [yN] y
Removing phpmyfaq_phpmyfaq_1   ... done
Removing phpmyfaq_yarn_1       ... done
Removing phpmyfaq_phpmyadmin_1 ... done
Removing elasticsearch-v6      ... done
Removing phpmyfaq_postgres_1   ... done
Removing phpmyfaq_composer_1   ... done
Removing phpmyfaq_mariadb_1    ... done

docker system prune --volumes
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all volumes not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Networks:
phpmyfaq_default

Total reclaimed space: 0B

docker-compose up
```

same output as yours, you got the error acutally as well.

if you then hit localhost:8080 -> redirect to http://localhost:8080/setup/index.php which stays blank

see your top part of your log from composer container
```
 thorsten@iMac  ~/htdocs/phpmyFAQ   master ? ↑1 ⍟1  docker-compose up                                                                                                                                                                                                                          ✔  3395  06:00:57
Creating network "phpmyfaq_default" with the default driver
Creating phpmyfaq_postgres_1   ... done
Creating elasticsearch-v6    ... done
Creating phpmyfaq_mariadb_1  ... done
Creating phpmyfaq_composer_1   ... done
Creating phpmyfaq_phpmyadmin_1 ... done
Creating phpmyfaq_yarn_1       ... done
Creating phpmyfaq_phpmyfaq_1   ... done
Attaching to elasticsearch-v6, phpmyfaq_mariadb_1, phpmyfaq_composer_1, phpmyfaq_postgres_1, phpmyfaq_phpmyadmin_1, phpmyfaq_yarn_1, phpmyfaq_phpmyfaq_1
elasticsearch-v6 | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
composer_1       | Loading composer repositories with package information
composer_1       | Installing dependencies from lock file
composer_1       | Dependency resolution completed in 0.000 seconds
composer_1       | Your requirements could not be resolved to an installable set of packages.
composer_1       | 
composer_1       |   Problem 1
composer_1       |     - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
composer_1       | 
phpmyadmin_1     | phpMyAdmin not found in /var/www/html - copying now...
phpmyfaq_composer_1 exited with code 2
```

**Comment by thorsten** [comment]
I merged a fix from the 3.0 branch into master, please try it again.

**Comment by pocketrocket** [comment]
@thorsten thanks for your fast replies on fixing this up.

while the current master is failing me with: 
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

if I revert the version tag in docker-compose.yml and remove the empty volumes line in postgres it's booting up fine for me:

```
git diff docker-compose.yml
diff --git i/docker-compose.yml w/docker-compose.yml
index de050d452..4a395dcc7 100644
--- i/docker-compose.yml
+++ w/docker-compose.yml
@@ -1,4 +1,4 @@
-version: '3.8'
+version: '2.3'

 # Use this file for development

@@ -27,7 +27,6 @@ services:
       - 5432:5432
     volumes:
       - ./volumes/postgres:/var/lib/postgresql/data
-      -
   phpmyfaq:
     build: .
     restart: always
```
