### ISSUE TITLE
Error when attempting to update from 2.9.13 to 3.0.8

### ISSUE THREAD

**Issue by manningtelfer** [thorsten/phpMyFAQ#1916]
**Describe the bug**
Receive "Error: Table faqconfig not found." when attempting to update from 2.9.13 to 3.0.8

**To Reproduce**

1. Go to 'http://[faq]/setup/update.php'
2. See error "Error: Table faqconfig not found."

**Expected behavior**
Expect to see update procedure (Steps 1 thru 3)

**Screenshots**
[Screenshot of Error](https://i.imgur.com/bfFBGEe.png)

**phpMyFAQ:**

- phpMyFAQ version: 2.9.13
- PHP version: 7.3.9
- Database: Microsoft SQL Server 2016
- Elasticsearch yes/no: No

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: 89.0.4389.114

**Additional context**
N/A

**Comment by thorsten** [comment]
@manningtelfer did you copy all new files over the existing ones?

**Comment by manningtelfer** [comment]
Yes, I followed you documentation exactly.

**Comment by thorsten** [comment]
It's really strange, I'll check it.

**Comment by thorsten** [comment]
Fixed for 3.0.9, the SQL query only worked with MySQL, sorry!

**Comment by manningtelfer** [comment]
I am able to complete the upgrade now, however the site throws a 500 - Internal server error with no further information. I enabled bootstrap logging but still not getting any further information about the error.

Succesful upgrade: https://imgur.com/JVw0pYn
Error: https://imgur.com/4w2Z7LZ

**Comment by thorsten** [comment]
Do you see any errors in our web servers log?
