### ISSUE TITLE
Embedding Youtube Video broken

### ISSUE THREAD

**Issue by kgoldinger** [thorsten/phpMyFAQ#1940]
**Describe the bug**
If I try to embedd a youtube video using the iframe link (provided by yt), TinyMCE seems to rip off the code

**To Reproduce**

1. Create new FAW
2. Insert Media
3. Tab Embed
4. Insert an <iframe> link of your choice
5. save

**Expected behavior**
The video should be correctly embedded

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.0.9
- PHP version: 7.4.6
- Database: mariadb 
- Elasticsearch yes/no: doesn't matter

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: Windows
- Browser [e.g. chrome, safari]: Edge, Chrome
- Version [e.g. 22]: 90

**Additional context**
As far as I see, this is caused by the following line of admin/footer.php (line# 171):
`invalid_elements: 'iframe,object,embed',`

this line was inserted in 3.0.8 and seems to break the possibility to embed yt videos.

**Comment by thorsten** [comment]
We had to change this due to a security issue in TinyMCE.

**Comment by kgoldinger** [comment]
So there's no way to embed yt videos anymore? our users are using this quite often... Do I compromise the system seriously  if I re-enable this feature by myself?

**Comment by thorsten** [comment]
No, it's a moderate issue: https://github.com/tinymce/tinymce/security/advisories/GHSA-w7jx-j77m-wp65

**Comment by thorsten** [comment]
Will be fixed with #1892

**Comment by thorsten** [comment]
We updated the upcoming version of phpMyFAQ v3.2 to TinyMCE v5.10 and so this issue is fixed as well

**Comment by sprklinginfo** [comment]
Hi, this issue is not fixed. We are using phpMyFAQ 3.1.7 and tried to embed a youtube video, but the link or embedded code is stripped off as soon as we save it. Is there a setting we need to change in order to embed a youtube video?

**Comment by thorsten** [comment]
It will be fixed with 3.2

**Comment by kgoldinger** [comment]
Hi Thorsten
I've begun to Test 3.2RC2, but it seems that I'm still unable to embedd youtube videos. Furthermore it seems that I cannot edit the tinyMCE.init() to change the editors behaviour, without recompiling the webpack stuff... is this correct?

**Comment by thorsten** [comment]
I'll re-check the issue again.

**Comment by thorsten** [comment]
Our HTML Sanitizer removes the embedded iframe, I'll investigate that.

**Comment by antonio-hickey** [comment]
> So there's no way to embed yt videos anymore? our users are using this quite often... Do I compromise the system seriously if I re-enable this feature by myself?

Where you able to manually re-enable this feature, if so how?
