### ISSUE TITLE
Some input PANELs do not close

### ISSUE THREAD

**Issue by antoniomch** [thorsten/phpMyFAQ#2206]
**Describe the bug**
Some input PANELs do not close or refresh
Like de add new user, in administration 
Or Adding a FAQ via front hend

**To Reproduce**

1. Adding a new user in administration
2. Fill the information 
3. click save
4. All fields check OK, I know the user is added, but the input panel do not close

Other example
Adding a FAQ in the front end LINK
http://<IP>/<phpmyfaq site>/index.php?action=add&cat=0
I fill all the needed fields for the FAQ, I click SAVE, but the screen remains as is, no change at all
But I know that its saved because I can see it in the approval state
The felling is that nothing happened, and the person clicks again and again on save...
And then there are a ton of equal FAQ0s to approve

**Screenshots**

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.4
- PHP version 8.0.19
- Database mysql  Ver 15.1 Distrib 10.7.4-MariaDB
- Elasticsearch no

**Desktop (please complete the following information):**
Happens in any PC or browser

**Comment by thorsten** [comment]
The cookie message banner is already fixed, please upgrade to 3.1.6

**Comment by antoniomch** [comment]
Will it solve the other issues too ?

**Comment by thorsten** [comment]
I'm on vacation, maybe, I fixed some other related issues.

**Comment by antoniomch** [comment]
I've upgraded to 3.1.6
And some issues still persist
Add new user, in administration, does not close de panel after clicking SAVE
Or Adding a FAQ via front end, the user fills the fields, clicks save, very briefly appears Saving at the bottom, but after that the screen remains the same, the user has the felling that it was not saved when it was

**Comment by thorsten** [comment]
Yes, I'm working on both issues. I could reproduce both of them.

**Comment by antoniomch** [comment]
This appears in apache error log

```
[Tue Sep 20 12:32:49.648951 2022] [php:notice] [pid 47035] [client 10.188.146.105:55054] 
phpMyFAQ TypeError: phpMyFAQ\\Notification::sendNewFaqAdded(): Argument #3 ($faqLanguage) must be of type string, null given, 
called in /var/www/html/mocho/ajaxservice.php on line 446 in /var/www/html/mocho/src/phpMyFAQ/Notification.php on line 81
\nStack trace:\n#0 /var/www/html/mocho/ajaxservice.php(446): phpMyFAQ\\Notification->sendNewFaqAdded()\n#1 {main}, referer: http://10.131.42.138/mocho/index.php?action=add&cat=0
```

**Comment by thorsten** [comment]
Fixed now for 3.1.7
