### ISSUE TITLE
Formatting errors in the FAQs

### ISSUE THREAD

**Issue by menkey2k** [thorsten/phpMyFAQ#2562]
I discovered another bug. The browser makes no difference. RC3

![image](https://github.com/thorsten/phpMyFAQ/assets/89402232/5fba4b0b-0cb4-45bc-830d-4928cae56da5)

**Comment by thorsten** [comment]
Is it the category breadcrumb?

**Comment by menkey2k** [comment]
Yes.

**Comment by thorsten** [comment]
That was fixed in 3.1 but not merged yet, see #2553 

Here's the fix, should work in 3.2 as well

**Comment by kgoldinger** [comment]
Hi Torsten

It seems that the issue still exists in RC3

Best regards
Kay

**Comment by thorsten** [comment]
It'll be fixed with the final 3.2.0 release.
